const nome = prompt("Digite seu nome: ")
document.body.innerHTML += `O seu nome é: ${nome}<br />`
document.body.innerHTML += `Seu nome tem ${nome.length} letras <br />`;
document.body.innerHTML += `A segunda letra do seu nome é: ${nome[1]}<br />`;
document.body.innerHTML += `Qual o primeiro índice da letra E no seu nome? ${nome.indexOf("e")}<br />`;
document.body.innerHTML += `Qual o último índice da letra E no seu nome? ${nome.lastIndexOf("e")}<br />`;
document.body.innerHTML += `As últimas 3 letras do seu nome são: ${nome.slice(20,23)}<br />`;
document.body.innerHTML += `As palavras do seu nome são: ${nome.slice(0,5)}, ${nome.slice(6,12)}, ${nome.slice(13,17)}, ${nome.slice(17,24)}<br />`;
document.body.innerHTML += `Seu nome com letras maiúsculas: ${nome.toUpperCase()}<br />`;
document.body.innerHTML += `Seu nome com letras minúsculas: ${nome.toLowerCase()}<br />`;